use_frameworks!

target 'SRMCategory_Example' do
  pod 'SRMCategory', :path => '../'

  target 'SRMCategory_Tests' do
    inherit! :search_paths
  end

  target 'SRMCategory_ExampleUITests' do
    inherit! :search_paths
  end
end
